name: Build SAMPHP

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_WORKSPACE: "/usr/local/"

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-multilib g++-multilib libxml2-dev git

    - name: Update CMake
      run: |
        sudo apt-get purge --auto-remove cmake
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Download SAMPSDK
      run: |
        git clone https://github.com/udan11/samp-plugin-sdk.git samp-sdk
        mkdir -p ${{env.GITHUB_WORKSPACE}}/samp-sdk
        cp -r samp-sdk/include ${{env.GITHUB_WORKSPACE}}/samp-sdk/include

    - name: Clone SAMPGDK
      run: |
        git clone https://github.com/samp-forks/sampgdk.git
        cd sampgdk
        mkdir build
        cd build
        cmake -DSAMPSDK_DIR=${{env.GITHUB_WORKSPACE}}/samp-sdk ..
        make

    - name: Build SAMPHP
      run: |
        chmod +x install_libphp5.sh
        ./install_libphp5.sh ${{env.GITHUB_WORKSPACE}}/samp-sdk
        chmod +x build.sh
        ./build.sh

    - name: Archive Build
      uses: actions/upload-artifact@v3
      with:
        name: samphp-plugin
        path: samphp
